# Configuration of linters.

run:
  modules-download-mode: mod
  timeout: 1m

output:
  sort-results: true

linters:
  enable:
    - asciicheck
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exhaustruct
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - ifshort
    - importas
    - ineffassign
    - ireturn
    - lll
    - maintidx
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilnil
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - unconvert
    - unused
    - varcheck
    - varnamelen
    - whitespace
    - wrapcheck

linters-settings:
  exhaustruct:
    exclude:
      - 'config\.Rule'
  gocyclo:
    min-complexity: 15
  gofumpt:
    extra-rules: true
    lang-version: 1.18
  gomnd:
    ignored-numbers:
      - "2"
      - "3"
      - "10"
  staticcheck:
    checks: ["all"]
  tenv:
    all: true
