= Archivo de configuración de Fairú

Este documento describe la estructura del archivo de configuración de Fairú.

Fairú se diseñó para ser una utilidad para ordenar archivos muy flexible y
rápida, además de ser muy fácil de configurar.

La configuración utiliza YAML como formato, lo que permite una sintaxis muy
clara y comprensible.

La configuración se divide en dos grandes secciones:

. Opciones de configuración: Aquí puedes ajustar opciones ajenas al
ordenamiento de los archivos; como los colores de la terminal o el uso de
CPUS.

. Organización de archivos: Aquí se define la manera en que son tratados los
archivos.

== Opciones de configuración

// TODO(anderson-lt): Describir esta parte.

== Organización de archivos

Este sistema se basa en un lenguaje de instrucciones simples y bien definidas:

La estructura se basa en un sistema de filtros y acciones; si un filtro no es
superado, se intenta con el siguiente...

.Demostración del flujo de ejecución.
----
Grupo 1:
  Filtro 1: Argumentos...
  Filtro 2: Argumentos...
  Acción: Argumentos...

Grupo 2:
  Filtro: Argumentos...
  Acción: Argumentos...

Grupo 3:
  Filtro: Argumentos...
  Acción 1: Argumentos...
  Acción 2: Argumentos...
----
El archivo pasa por el _Grupo 1_, si logra pasar todos sus filtros, se aplican
las acciones definidas en este grupo, de so contrario, se intenta con el
_Grupo 2_, si pasa su filtro, se ejecuta la acción definida, si no logra pasar
su filtro, se intenta con el _Grupo 3_ de la misma forma que los anteriores;
si se llega al final de todos los grupos sin pasar los filtros necesarios, se
ignora el archivo.

=== Lista de filtros

Un filtro se compone de una clave de diccionario YAML indicando el filtro a
usar, opcionalmente los filtros pueden tener una versión negada, la cual se 
utiliza al añadir un carácter `!` al final del nombre, en la versión negada el
filtro rechazará lo que acepta en su versión normal y aceptará lo que rechaza
en su versión normal.

== Por nombre

Estos filtros se basan únicamente en el nombre del archivo:

Name::
Este filtro aceptará todos los archivos que contengan el nombre
especificado.
+
.Sintaxis de `Name`.
----
Name: NombreDeArchivo
Name:
  - Archivo1
  - Archivo2
Name: [Archivo1, Archivo2]
----

// TODO(anderson-lt): Hacer esto más detallado.
Glob::
Este filtro aceptará todos los archivos que coincidan con los «Unix Shell
Glob» proveídos.

Pattern::
Similar a `Glob`, pero acepta una expresión regular.

== Por tipo

Type::
Este filtro acepta todos los archivos que sean del tipo especificado.

Identifier::
Este filtro acepta todos los archivos que tengan los «números mágicos»
especificados.

== Por tamaño

Size::
Este filtro aceptará todos los archivos que tengan el mismo tamaño
especificado, o uno mayor.

Consumes::
Este filtro acepta exactamente dos argumentos, ambos refiriéndose a tamaño de
archivo, esto es para especificar un rango de tamaño (inclusive), para aceptar
archivos.

=== Lista de acciones

Las acciones son operaciones que se ejecutan una vez todos los filtros son
pasados. Las acciones aceptan una versión alternativa que se activa al añadir
un carácter `!` al final del nombre.

==== Acciones de registro

Las acciones de registro le permiten llevar un registro de todo lo que hace
_Fairú_ y ayudarle en labores de depuración.

Todas las acciones de registro aceptan una sintaxis especial (conocida como
sintaxis de shell), que le permite añadir información adicional de las
variables de entorno:

----
$Variable # <- Imprime el valor de la variable de entorno Variable.
$$Variable # <- Imprime literalmente $Variable.
$VariableQueNoExiste # No imprime nada.
----

Print::
Imprime sus argumentos en la salida estándar separados pon un espacio y añade
un salto de línea al final.

Write::
Imprime sus argumentos en la salida estándar, estos se imprimen uno después
del otro y no se imprime ningún salto de línea.

Report::
Como `Print`, pero, imprime en la salida de error estándar.

Error::
Como `Write`, pero, imprime en la salida de error estándar.

// TODO(anderson-lt): Añadir formato.
//Copy # Copia lo que sea.
//CopyDir
//CopyFile
//
//Move
//MoveDir
//MoveFile
//
//Delete
//DeleteFile
//DeleteDir
//
//# Miscélanea:
//If:
//  - null # Condición
//  - null # Hacer si es cierto
//If!: null # If negado.
//
//# Negación
//False:
//True!:
//# Verdad.
//  True:
//  False!:
//
//
//# Salida (requiere código).
//Return: normal
//Exit: normal
//
//# Shell regex (aplican reglas de fish shell).
//Shell: command args
//System: raw shell
//
//# Funciones.
//Function: # Practicamente puedes añadir lo que deses aqui.
//  - Basura
//  - &MyFunc MyFunc:  # La idea es añadir referencias YAML aquí.
//    #Cmds....
//  - &ref Log:
//      Print: Hola Mundo.
//      Show: version
//
//# Aunque puedes soltar la referencia directamente, la idea es usar call para
//# mayor clariad.
//    Call: *anyRef
//
//# Recurse mira la recursión en base al directorio actual.
//    Recurse: int # Si es mayor a int, fallar.
//    Recurse!: int # Si es menor, fallar.
//
//
//
//Operation Title:
//  - Type: python
//  - Glob!: '*.py'
//  - Delete:
//  - Call: *ref # Ejemplo de call.
