
== Filters

=== By Name

==== Name
It coincides with the names given or its final part.

.Filter `Name`
====
The instruction: `Name: ["Gopher", "home/blue"]` matches with:

* `Gopher`                   -> `Gopher`
* `home/blue`                -> `home/blue`
* `hello/Gopher`             -> `Gopher`
* `home/blue/Gopher`         -> `Gopher`
* `chroot/environ/home/blue` -> `home/blue`

But, not with:

* `MyGopher`
* `home/blue/color`
* `home/color/blue`
* `Gopher/Blue`
* `pher/home/blu`
====

==== Glob
This accepts the files that match the specified _glob_.

.Syntax of Glob (from Go Documentation)
....
{ term }

term:
  '*'         matches any sequence of non-Separator characters
  '?'         matches any single non-Separator character
  '[' [ '^' ] { character-range } ']'
              character class (must be non-empty)
  c           matches character c (c != '*', '?', '\\', '[')
  '\\' c      matches character c

character-range:
  c           matches character c (c != '\\', '-', ']')
  '\\' c      matches character c
  lo '-' hi   matches character c for lo <= c <= hi
....

NOTE: We use the implementation offered by the Go programming language, which
presents a peculiarity that makes the character `*` also coincides with the
character `.` (dot).

.Filter `Glob`
====
The instruction: `Glob: 'Image*'` matches with:

* `Image`
* `Image1`
* `ImageAmazing`
* `Image.png`
* `ImageAny.svg`
====

==== Pattern
// TODO: Add description.
